// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	server "github.com/canonical/workspace/internal/server"
	mock "github.com/stretchr/testify/mock"
)

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

// Exec provides a mock function with given fields: name, user, command
func (_m *MockServer) Exec(name string, user string, command []string) error {
	ret := _m.Called(name, user, command)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(name, user, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWorkspaceDevices provides a mock function with given fields: name
func (_m *MockServer) GetWorkspaceDevices(name string) (server.WorkspaceDevices, error) {
	ret := _m.Called(name)

	var r0 server.WorkspaceDevices
	if rf, ok := ret.Get(0).(func(string) server.WorkspaceDevices); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(server.WorkspaceDevices)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LaunchWorkspaceInstance provides a mock function with given fields: name, base
func (_m *MockServer) LaunchWorkspaceInstance(name string, base string) error {
	ret := _m.Called(name, base)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, base)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWorkspaceState provides a mock function with given fields: name, action
func (_m *MockServer) SetWorkspaceState(name string, action string) error {
	ret := _m.Called(name, action)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWorkspaceDevices provides a mock function with given fields: name, devices
func (_m *MockServer) UpdateWorkspaceDevices(name string, devices server.WorkspaceDevices) error {
	ret := _m.Called(name, devices)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, server.WorkspaceDevices) error); ok {
		r0 = rf(name, devices)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockServer(t mockConstructorTestingTNewMockServer) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
