// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	store "github.com/canonical/workspace/internal/fakestore"
	mock "github.com/stretchr/testify/mock"
)

// MockStoreClient is an autogenerated mock type for the StoreClient type
type MockStoreClient struct {
	mock.Mock
}

// FetchSDK provides a mock function with given fields: name, channel, destination
func (_m *MockStoreClient) FetchSDK(name string, channel string, destination string) (store.SdkBlob, error) {
	ret := _m.Called(name, channel, destination)

	var r0 store.SdkBlob
	if rf, ok := ret.Get(0).(func(string, string, string) store.SdkBlob); ok {
		r0 = rf(name, channel, destination)
	} else {
		r0 = ret.Get(0).(store.SdkBlob)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(name, channel, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockStoreClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStoreClient creates a new instance of MockStoreClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStoreClient(t mockConstructorTestingTNewMockStoreClient) *MockStoreClient {
	mock := &MockStoreClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
