// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	workspacebackend "github.com/canonical/workspace/internal/workspacebackend"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkspaceBackend is an autogenerated mock type for the WorkspaceBackend type
type MockWorkspaceBackend struct {
	mock.Mock
}

// AddWorkspaceConfig provides a mock function with given fields: name, project_id, item
func (_m *MockWorkspaceBackend) AddWorkspaceConfig(name string, project_id string, item *workspacebackend.WorkspaceConfigValue) error {
	ret := _m.Called(name, project_id, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *workspacebackend.WorkspaceConfigValue) error); ok {
		r0 = rf(name, project_id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWorkspaceDevice provides a mock function with given fields: name, project_id, props
func (_m *MockWorkspaceBackend) AddWorkspaceDevice(name string, project_id string, props workspacebackend.WorkspaceDevice) error {
	ret := _m.Called(name, project_id, props)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, workspacebackend.WorkspaceDevice) error); ok {
		r0 = rf(name, project_id, props)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWorkspacesConfig provides a mock function with given fields: filter, item
func (_m *MockWorkspaceBackend) AddWorkspacesConfig(filter workspacebackend.WorkspaceConfigFilter, item *workspacebackend.WorkspaceConfigValue) error {
	ret := _m.Called(filter, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(workspacebackend.WorkspaceConfigFilter, *workspacebackend.WorkspaceConfigValue) error); ok {
		r0 = rf(filter, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWorkspaceInstance provides a mock function with given fields: name, project_id
func (_m *MockWorkspaceBackend) DeleteWorkspaceInstance(name string, project_id string) error {
	ret := _m.Called(name, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: name, project_id, args
func (_m *MockWorkspaceBackend) Exec(name string, project_id string, args *workspacebackend.ExecArgs) (chan bool, error) {
	ret := _m.Called(name, project_id, args)

	var r0 chan bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *workspacebackend.ExecArgs) (chan bool, error)); ok {
		return rf(name, project_id, args)
	}
	if rf, ok := ret.Get(0).(func(string, string, *workspacebackend.ExecArgs) chan bool); ok {
		r0 = rf(name, project_id, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan bool)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *workspacebackend.ExecArgs) error); ok {
		r1 = rf(name, project_id, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspace provides a mock function with given fields: name, project_id
func (_m *MockWorkspaceBackend) GetWorkspace(name string, project_id string) (*workspacebackend.WorkspaceProps, error) {
	ret := _m.Called(name, project_id)

	var r0 *workspacebackend.WorkspaceProps
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*workspacebackend.WorkspaceProps, error)); ok {
		return rf(name, project_id)
	}
	if rf, ok := ret.Get(0).(func(string, string) *workspacebackend.WorkspaceProps); ok {
		r0 = rf(name, project_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workspacebackend.WorkspaceProps)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, project_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspacesByConfig provides a mock function with given fields: filter
func (_m *MockWorkspaceBackend) GetWorkspacesByConfig(filter workspacebackend.WorkspaceConfigFilter) ([]*workspacebackend.WorkspaceProps, error) {
	ret := _m.Called(filter)

	var r0 []*workspacebackend.WorkspaceProps
	var r1 error
	if rf, ok := ret.Get(0).(func(workspacebackend.WorkspaceConfigFilter) ([]*workspacebackend.WorkspaceProps, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(workspacebackend.WorkspaceConfigFilter) []*workspacebackend.WorkspaceProps); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*workspacebackend.WorkspaceProps)
		}
	}

	if rf, ok := ret.Get(1).(func(workspacebackend.WorkspaceConfigFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspacesByDevices provides a mock function with given fields: filter
func (_m *MockWorkspaceBackend) GetWorkspacesByDevices(filter workspacebackend.WorkspaceDeviceFilter) (map[string]*workspacebackend.WorkspaceProps, error) {
	ret := _m.Called(filter)

	var r0 map[string]*workspacebackend.WorkspaceProps
	var r1 error
	if rf, ok := ret.Get(0).(func(workspacebackend.WorkspaceDeviceFilter) (map[string]*workspacebackend.WorkspaceProps, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(workspacebackend.WorkspaceDeviceFilter) map[string]*workspacebackend.WorkspaceProps); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*workspacebackend.WorkspaceProps)
		}
	}

	if rf, ok := ret.Get(1).(func(workspacebackend.WorkspaceDeviceFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LaunchWorkspaceInstance provides a mock function with given fields: name, base, project_id
func (_m *MockWorkspaceBackend) LaunchWorkspaceInstance(name string, base string, project_id string) error {
	ret := _m.Called(name, base, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, base, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWorkspaceConfig provides a mock function with given fields: name, project_id, key
func (_m *MockWorkspaceBackend) RemoveWorkspaceConfig(name string, project_id string, key string) error {
	ret := _m.Called(name, project_id, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, project_id, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWorkspaceDevice provides a mock function with given fields: name, project_id, device
func (_m *MockWorkspaceBackend) RemoveWorkspaceDevice(name string, project_id string, device string) error {
	ret := _m.Called(name, project_id, device)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, project_id, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWorkspaceState provides a mock function with given fields: name, action, project_id
func (_m *MockWorkspaceBackend) SetWorkspaceState(name string, action string, project_id string) error {
	ret := _m.Called(name, action, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, action, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockWorkspaceBackend interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWorkspaceBackend creates a new instance of MockWorkspaceBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWorkspaceBackend(t mockConstructorTestingTNewMockWorkspaceBackend) *MockWorkspaceBackend {
	mock := &MockWorkspaceBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
