// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	server "github.com/canonical/workspace/internal/server"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkspaceServer is an autogenerated mock type for the WorkspaceServer type
type MockWorkspaceServer struct {
	mock.Mock
}

// AddWorkspaceConfig provides a mock function with given fields: names, project_id, item
func (_m *MockWorkspaceServer) AddWorkspaceConfig(names string, project_id string, item *server.WorkspaceConfigValue) error {
	ret := _m.Called(names, project_id, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *server.WorkspaceConfigValue) error); ok {
		r0 = rf(names, project_id, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWorkspaceDevice provides a mock function with given fields: name, project_id, props
func (_m *MockWorkspaceServer) AddWorkspaceDevice(name string, project_id string, props server.WorkspaceDevice) error {
	ret := _m.Called(name, project_id, props)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, server.WorkspaceDevice) error); ok {
		r0 = rf(name, project_id, props)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWorkspacesConfig provides a mock function with given fields: filter, item
func (_m *MockWorkspaceServer) AddWorkspacesConfig(filter server.WorkspaceConfigFilter, item *server.WorkspaceConfigValue) error {
	ret := _m.Called(filter, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(server.WorkspaceConfigFilter, *server.WorkspaceConfigValue) error); ok {
		r0 = rf(filter, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: name, project_id, args
func (_m *MockWorkspaceServer) Exec(name string, project_id string, args *server.ExecArgs) (chan bool, error) {
	ret := _m.Called(name, project_id, args)

	var r0 chan bool
	if rf, ok := ret.Get(0).(func(string, string, *server.ExecArgs) chan bool); ok {
		r0 = rf(name, project_id, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, *server.ExecArgs) error); ok {
		r1 = rf(name, project_id, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspacesByConfig provides a mock function with given fields: filter
func (_m *MockWorkspaceServer) GetWorkspacesByConfig(filter server.WorkspaceConfigFilter) ([]*server.WorkspaceProps, error) {
	ret := _m.Called(filter)

	var r0 []*server.WorkspaceProps
	if rf, ok := ret.Get(0).(func(server.WorkspaceConfigFilter) []*server.WorkspaceProps); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*server.WorkspaceProps)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(server.WorkspaceConfigFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspacesByDevices provides a mock function with given fields: filter
func (_m *MockWorkspaceServer) GetWorkspacesByDevices(filter server.WorkspaceDeviceFilter) (map[string]*server.WorkspaceProps, error) {
	ret := _m.Called(filter)

	var r0 map[string]*server.WorkspaceProps
	if rf, ok := ret.Get(0).(func(server.WorkspaceDeviceFilter) map[string]*server.WorkspaceProps); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*server.WorkspaceProps)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(server.WorkspaceDeviceFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *MockWorkspaceServer) DeleteWorkspaceInstance(name, project_id string) error {
	ret := _m.Called(name, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// LaunchWorkspaceInstance provides a mock function with given fields: name, base, project_id
func (_m *MockWorkspaceServer) LaunchWorkspaceInstance(name string, base string, project_id string) error {
	ret := _m.Called(name, base, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, base, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWorkspaceConfig provides a mock function with given fields: name, project_id, key
func (_m *MockWorkspaceServer) RemoveWorkspaceConfig(name string, project_id string, key string) error {
	ret := _m.Called(name, project_id, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, project_id, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWorkspaceDevice provides a mock function with given fields: name, project_id, device
func (_m *MockWorkspaceServer) RemoveWorkspaceDevice(name string, project_id string, device string) error {
	ret := _m.Called(name, project_id, device)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, project_id, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWorkspaceState provides a mock function with given fields: name, action, project_id
func (_m *MockWorkspaceServer) SetWorkspaceState(name string, action string, project_id string) error {
	ret := _m.Called(name, action, project_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, action, project_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockWorkspaceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWorkspaceServer creates a new instance of MockWorkspaceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWorkspaceServer(t mockConstructorTestingTNewMockWorkspaceServer) *MockWorkspaceServer {
	mock := &MockWorkspaceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
