repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.2.1
    hooks:
      - id: golangci-lint
      - id: golangci-lint
        alias: errcheck
        name: errcheck
        args:
          - --config=.golangci.errcheck.yaml
