repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint
      - id: golangci-lint
        alias: golangci-incremental
        name: golangci-incremental
        args:
          - --config=.golangci.incremental.yaml

  - repo: local
    hooks:
      - id: docs-check
        name: Run docs check with Workshop
        entry: make -C docs/ spelling linkcheck woke lint-md
        language: system
        pass_filenames: false
        files: ^docs/.*\.(rst|md|txt|json)$
