project: workshop

environment:
      PATH: $PATH:~/go/bin
      WORKSHOP: /var/lib/workshop/default
      TESTSLIB: $SPREAD_PATH/tests/lib
      SDKCONTENT: $SPREAD_PATH/tests/lib/sdk
      SDK_STORE_BUCKET_DIR: /data/sdk-store

prepare: |
      . "$TESTSLIB"/utils.sh

      apt-get install -y --no-install-recommends jq
      snap install go --classic

      snap install lxd --classic
      cd /remote; GOBIN=/usr/bin go install -buildvcs=false /remote/cmd/workshop/
      lxd init --auto

      # run fake GCS bucket storage to emulate SDK store
      publish_test_sdk_content "$SDKCONTENT" "$SDK_STORE_BUCKET_DIR"
      /bin/sh -c "nohup go run github.com/fsouza/fake-gcs-server@latest -data /data -scheme http -port 8080 -public-host localhost:8080 > ~/fake_sdk_store.log 2>&1 &"


      echo "Waiting fake SDK store to launch on 8080..."
      while ! nc -z localhost 8080; do
        sleep 0.1 # wait for 1/10 of the second before check again
      done

debug: |
      lxc list -f compact --all-projects

restore: |
      rm -rf /data
      rm -rf /storage
backends:
  multipass:
    type: adhoc
    allocate: |
      if [ "$SPREAD_SYSTEM" = "ubuntu-24.04-64" ]; then
          image="daily:devel"
          instance_name=spread-devel
      else
          # SPREAD_SYSTEM has the following format here 'ubuntu-XX.YY-64' and gets
          # translated to an image XX.YY.
          image=$(echo $SPREAD_SYSTEM | sed -e 's/ubuntu-\(.*\)-64/\1/')
          instance_name="spread-${image/./}"
      fi
      if [ -z "${image}" ]; then
        FATAL "$SPREAD_SYSTEM is not supported!"
      fi
      multipass launch --disk 20G --memory 8G --cpus 8 --name "$instance_name" "$image"
      # Get the IP from the instance
      ip=$(multipass info --format csv "$instance_name" | tail -1 | cut -d\, -f3)
      # Enable PasswordAuthertication for root over SSH.
      multipass exec "$instance_name" -- \
        sudo sh -c "echo root:ubuntu | sudo chpasswd"
      multipass exec "$instance_name" -- \
        sudo sh -c \
        "sed -i /etc/ssh/sshd_config -e 's/^PasswordAuthentication.*/PasswordAuthentication yes/' -e 's/^#PermitRootLogin.*/PermitRootLogin yes/'"
      multipass exec "$instance_name" -- \
        sudo systemctl restart ssh
      ADDRESS "$ip:22"
    discard: |
      if [ "$SPREAD_SYSTEM" = "ubuntu-24.04-64" ]; then
          image="daily:devel"
          instance_name=spread-devel
      else
          # SPREAD_SYSTEM has the following format here 'ubuntu-XX.YY-64' and gets
          # translated to an image XX.YY.
          image=$(echo $SPREAD_SYSTEM | sed -e 's/ubuntu-\(.*\)-64/\1/')
          instance_name="spread-${image/./}"
      fi
      if [ -z "${image}" ]; then
        FATAL "$SPREAD_SYSTEM is not supported!"
      fi
      multipass delete --purge "$instance_name"
    systems:
      - ubuntu-22.04-64:
          workers: 1
          username: root
          password: ubuntu
suites:
  tests/main/:
    summary: Core workshop scenarios
  tests/integration/:
    summary: LXD integration tests

path: /remote
exclude:
  - .git
  - .workshop.lock
  - docs
