project: workshop
path: /workshop
environment:
  PATH: $PATH:~/go/bin
  PROJECT_PATH: /workshop
  TESTSLIB: $PROJECT_PATH/tests/lib
  SDKS: $PROJECT_PATH/tests/lib/sdk
  SDK_STORE_BUCKET_DIR: /data/sdk-store
  IMAGE_SERVER: $(HOST:echo -n $WORKSHOP_IMAGE_SERVER)
repack: |
  test -f tests/*.snap || snapcraft -o tests/
  cat <&3 >&4
backends:
  lxd:
    systems:
      - ubuntu-24.04:
          workers: 2
suites:
  tests/main/:
    summary: Core workshop scenarios
    prepare: |
      . "$TESTSLIB"/utils.sh
      prepare_environment
      start_sdk_store
    restore: |
      . "$TESTSLIB"/utils.sh
      stop_sdk_store
      cleanup_environment
    debug: |
      lxc list --project workshop.ubuntu
      sudo -u ubuntu 2>&1 -- workshop list --global
    kill-timeout: 30m
  tests/integration/:
    summary: LXD integration tests
    prepare: |
      . "$TESTSLIB"/utils.sh
      setup_lxd
      snap install go --classic --channel=1.23/stable
    kill-timeout: 30m
  tests/documentation/:
    summary: Documentation tests
    prepare: |
      . "$TESTSLIB"/utils.sh
      prepare_environment
      start_sdk_store
    restore: |
      . "$TESTSLIB"/utils.sh
      stop_sdk_store
      cleanup_environment
    kill-timeout: 30m
exclude:
  - .git
  - .workshop.lock
  - docs
  - __debug_bin*
