project: workspace

backends:
  qemu:
    systems:
      - ubuntu-22.10-64:
          username: ubuntu
          password: ubuntu
suites:
  tests/core/:
    summary: Core workspace scenarios
    environment: 
      PATH: $PATH:~/go/bin
    prepare: |
      apt-get update
      apt-get install -y --no-install-recommends gcc libc6-dev snapd
      snap install go --classic

      snap install lxd --classic
      cd /remote; GOBIN=/usr/bin go install -buildvcs=false /remote/cmd/workspace/
      lxd init --auto

path: /remote