// Copyright (c) 2026 Canonical Ltd
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/workshop/internal/https (interfaces: RequestRecorder,RoundTripper)
//
// Generated by this command:
//
//	mockgen -typed -package https -destination client_mock_test.go github.com/canonical/workshop/internal/https RequestRecorder,RoundTripper
//

// Package https is a generated GoMock package.
package https

import (
	http "net/http"
	url "net/url"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestRecorder is a mock of RequestRecorder interface.
type MockRequestRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRecorderMockRecorder
	isgomock struct{}
}

// MockRequestRecorderMockRecorder is the mock recorder for MockRequestRecorder.
type MockRequestRecorderMockRecorder struct {
	mock *MockRequestRecorder
}

// NewMockRequestRecorder creates a new mock instance.
func NewMockRequestRecorder(ctrl *gomock.Controller) *MockRequestRecorder {
	mock := &MockRequestRecorder{ctrl: ctrl}
	mock.recorder = &MockRequestRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRecorder) EXPECT() *MockRequestRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockRequestRecorder) Record(method string, arg1 *url.URL, res *http.Response, rtt time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", method, arg1, res, rtt)
}

// Record indicates an expected call of Record.
func (mr *MockRequestRecorderMockRecorder) Record(method, arg1, res, rtt any) *MockRequestRecorderRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRequestRecorder)(nil).Record), method, arg1, res, rtt)
	return &MockRequestRecorderRecordCall{Call: call}
}

// MockRequestRecorderRecordCall wrap *gomock.Call
type MockRequestRecorderRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestRecorderRecordCall) Return() *MockRequestRecorderRecordCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestRecorderRecordCall) Do(f func(string, *url.URL, *http.Response, time.Duration)) *MockRequestRecorderRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestRecorderRecordCall) DoAndReturn(f func(string, *url.URL, *http.Response, time.Duration)) *MockRequestRecorderRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecordError mocks base method.
func (m *MockRequestRecorder) RecordError(method string, arg1 *url.URL, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordError", method, arg1, err)
}

// RecordError indicates an expected call of RecordError.
func (mr *MockRequestRecorderMockRecorder) RecordError(method, arg1, err any) *MockRequestRecorderRecordErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordError", reflect.TypeOf((*MockRequestRecorder)(nil).RecordError), method, arg1, err)
	return &MockRequestRecorderRecordErrorCall{Call: call}
}

// MockRequestRecorderRecordErrorCall wrap *gomock.Call
type MockRequestRecorderRecordErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestRecorderRecordErrorCall) Return() *MockRequestRecorderRecordErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestRecorderRecordErrorCall) Do(f func(string, *url.URL, error)) *MockRequestRecorderRecordErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestRecorderRecordErrorCall) DoAndReturn(f func(string, *url.URL, error)) *MockRequestRecorderRecordErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRoundTripper is a mock of RoundTripper interface.
type MockRoundTripper struct {
	ctrl     *gomock.Controller
	recorder *MockRoundTripperMockRecorder
	isgomock struct{}
}

// MockRoundTripperMockRecorder is the mock recorder for MockRoundTripper.
type MockRoundTripperMockRecorder struct {
	mock *MockRoundTripper
}

// NewMockRoundTripper creates a new mock instance.
func NewMockRoundTripper(ctrl *gomock.Controller) *MockRoundTripper {
	mock := &MockRoundTripper{ctrl: ctrl}
	mock.recorder = &MockRoundTripperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoundTripper) EXPECT() *MockRoundTripperMockRecorder {
	return m.recorder
}

// RoundTrip mocks base method.
func (m *MockRoundTripper) RoundTrip(arg0 *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoundTrip", arg0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoundTrip indicates an expected call of RoundTrip.
func (mr *MockRoundTripperMockRecorder) RoundTrip(arg0 any) *MockRoundTripperRoundTripCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoundTrip", reflect.TypeOf((*MockRoundTripper)(nil).RoundTrip), arg0)
	return &MockRoundTripperRoundTripCall{Call: call}
}

// MockRoundTripperRoundTripCall wrap *gomock.Call
type MockRoundTripperRoundTripCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoundTripperRoundTripCall) Return(arg0 *http.Response, arg1 error) *MockRoundTripperRoundTripCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoundTripperRoundTripCall) Do(f func(*http.Request) (*http.Response, error)) *MockRoundTripperRoundTripCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoundTripperRoundTripCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockRoundTripperRoundTripCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
