#!/bin/sh

GCS_STORE_URL=$(snapctl get gcs.url)
export GCS_STORE_URL

WORKSHOP_IMAGE_SERVER=$(snapctl get workshop.image.server.url)
export WORKSHOP_IMAGE_SERVER

read -r sbpid _ < /proc/self/stat
export LISTEN_PID="${sbpid}"

# shellcheck disable=SC2086
exec "$SNAP"/bin/workshopd run --create-dirs
