name: dev
base: ubuntu@24.04
sdks:
  - name: go
    channel: 1.26/stable
  - name: project-tools
  - name: system
    plugs:
      sphinx-build:
        interface: tunnel
        endpoint: 8000
actions:
  docs-html: |
    make -C docs/ DOCS_VENVDIR="$HOME/.docs-venv" html
  docs-run: |
    make -C docs/ DOCS_VENVDIR="$HOME/.docs-venv" run
  docs-clean: |
    make -C docs/ clean-doc
  docs-check: |
    make -C docs/ DOCS_VENVDIR="$HOME/.docs-venv" spelling linkcheck woke lint-md
  lint: |
    golangci-lint run
    golangci-lint run --new-from-rev='HEAD~' --config=.golangci.incremental.yaml
  shellcheck: |
    git ls-files | file --mime-type -Nnf- | grep shellscript | cut -f1 -d: | xargs shellcheck --check-sourced --external-sources
    /opt/snapd-testing-tools/utils/spread-shellcheck tests/integration
  cover: |
    go test -covermode=count -coverpkg=./... -coverprofile=coverage.out ./...
