// Copyright (c) 2026 Canonical Ltd
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/workshop/internal/sdkstore (interfaces: RESTClient)
//
// Generated by this command:
//
//	mockgen -typed -package sdkstore -destination http_mock_test.go github.com/canonical/workshop/internal/sdkstore RESTClient
//

// Package sdkstore is a generated GoMock package.
package sdkstore

import (
	context "context"
	http "net/http"
	reflect "reflect"

	path "github.com/canonical/workshop/internal/sdkstore/path"
	gomock "go.uber.org/mock/gomock"
)

// MockRESTClient is a mock of RESTClient interface.
type MockRESTClient struct {
	ctrl     *gomock.Controller
	recorder *MockRESTClientMockRecorder
	isgomock struct{}
}

// MockRESTClientMockRecorder is the mock recorder for MockRESTClient.
type MockRESTClientMockRecorder struct {
	mock *MockRESTClient
}

// NewMockRESTClient creates a new mock instance.
func NewMockRESTClient(ctrl *gomock.Controller) *MockRESTClient {
	mock := &MockRESTClient{ctrl: ctrl}
	mock.recorder = &MockRESTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRESTClient) EXPECT() *MockRESTClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRESTClient) Get(arg0 context.Context, arg1 path.Path, arg2 any) (restResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(restResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRESTClientMockRecorder) Get(arg0, arg1, arg2 any) *MockRESTClientGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRESTClient)(nil).Get), arg0, arg1, arg2)
	return &MockRESTClientGetCall{Call: call}
}

// MockRESTClientGetCall wrap *gomock.Call
type MockRESTClientGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRESTClientGetCall) Return(arg0 restResponse, arg1 error) *MockRESTClientGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRESTClientGetCall) Do(f func(context.Context, path.Path, any) (restResponse, error)) *MockRESTClientGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRESTClientGetCall) DoAndReturn(f func(context.Context, path.Path, any) (restResponse, error)) *MockRESTClientGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Post mocks base method.
func (m *MockRESTClient) Post(arg0 context.Context, arg1 path.Path, arg2 http.Header, arg3, arg4 any) (restResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(restResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockRESTClientMockRecorder) Post(arg0, arg1, arg2, arg3, arg4 any) *MockRESTClientPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockRESTClient)(nil).Post), arg0, arg1, arg2, arg3, arg4)
	return &MockRESTClientPostCall{Call: call}
}

// MockRESTClientPostCall wrap *gomock.Call
type MockRESTClientPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRESTClientPostCall) Return(arg0 restResponse, arg1 error) *MockRESTClientPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRESTClientPostCall) Do(f func(context.Context, path.Path, http.Header, any, any) (restResponse, error)) *MockRESTClientPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRESTClientPostCall) DoAndReturn(f func(context.Context, path.Path, http.Header, any, any) (restResponse, error)) *MockRESTClientPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
