name: workshop
title: Workshop
base: core24
adopt-info: workshop
summary: A tool for defining and handling ephemeral development environments
description: |
  List your dependencies and components in YAML to define an environment.

  The key pieces of a definition are SDKs, independent but connectable units of
  functionality created by software publishers and available on the SDK Store.
  Workshop simplifies experiments with your environment layout.

  With Workshop, you can launch a setup that previously took hours to configure
  in a few commands and be sure that it stays operational. It assists in issue
  reproduction, enables hands-on code reviews and turns environment updates into
  manageable transactions, reducing the need to battle with your tooling every
  day.

confinement: classic
apps:
  workshop:
    environment:
      WORKSHOP_SOCKET: $SNAP_COMMON/workshop/workshop.socket
    command: bin/workshop
    completer: workshop-completer.sh
  workshopd:
    environment:
      PATH: ${SNAP}/usr/bin:${PATH}
      WORKSHOP: ${SNAP_DATA}
      WORKSHOP_CACHE: $SNAP_COMMON/workshop/cache
      WORKSHOP_SOCKET: $SNAP_COMMON/workshop/workshop.socket
    command: commands/run_daemon
    daemon: notify
    restart-condition: on-failure
    sockets:
      unix:
        listen-stream: $SNAP_COMMON/workshop/workshop.socket
        socket-mode: 0666
    plugs:
      - network-bind
  workshopctl:
    command: bin/workshopctl
  sdk:
    environment:
      WORKSHOP_SOCKET: $SNAP_COMMON/workshop/workshop.socket
    command: bin/sdk
parts:
  workshop:
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go/1.24/stable
    build-environment:
      - CGO_LDFLAGS_ALLOW: ".*"
    override-build: |
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]]; then
       export CGO_LDFLAGS="-Wl,-rpath=/snap/core24/current/usr/lib/x86_64-linux-gnu -Wl,--disable-new-dtags -Wl,-dynamic-linker=/snap/core24/current/lib64/ld-linux-x86-64.so.2"
      elif [[ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ]]; then
        export CGO_LDFLAGS="-Wl,-rpath=/snap/core24/current/lib/aarch64-linux-gnu -Wl,--disable-new-dtags -Wl,-dynamic-linker=/snap/core24/current/lib/ld-linux-aarch64.so.1"
      fi
      CGO_ENABLED=0 go build -o "${CRAFT_PART_INSTALL}/bin/workshop" ./cmd/workshop
      go build -o "${CRAFT_PART_INSTALL}/bin/workshopd" ./cmd/workshopd
      CGO_ENABLED=0 go build -o "${CRAFT_PART_INSTALL}/bin/workshopctl" ./cmd/workshopctl
      CGO_ENABLED=0 go build -o "${CRAFT_PART_INSTALL}/bin/sdk" ./cmd/sdk

      # Generate completions script
      "${CRAFT_PART_INSTALL}/bin/workshop" completion bash > "${CRAFT_PART_INSTALL}/workshop-completer.sh"

      # Set snap version
      VERSION="$("${CRAFT_PART_INSTALL}/bin/workshop" --version)"
      craftctl set version="$VERSION"
    stage-packages:
      - zstd
    prime:
      - bin/workshop
      - bin/workshopd
      - bin/workshopctl
      - bin/sdk
      - workshop-completer.sh
  wrappers:
    plugin: dump
    source: snap/local/
    organize:
      hooks/: snap/hooks/
      lib/: snap/lib/
