#!/bin/bash -e

# shellcheck source=snap/local/lib/lxc-utils
. "$SNAP/snap/lib/lxc-utils"

projects=$(get_projects)

for p in $(echo "$projects" | xargs -L1 echo); do
    echo "Found LXD project: $p"
    remove_instances "$p"
    remove_profiles "$p"
done

remove_volumes

# Reset workshop state
if [ -n "$SNAP_DATA" ]; then
    rm -rf "${SNAP_DATA:?}"/*
fi
