#!/bin/sh -e

# disable check for relative dir following
# shellcheck disable=SC1091
. "$(dirname "$0")/lxc-utils"

projects=$(get_projects)

for p in $(echo "$projects" | xargs -L1 echo); do
  echo "Found LXD project: $p" 
  remove_instances "$p"
  remove_profiles "$p"
done 

remove_volumes

# Reset workshop state
rm -rf /var/snap/workshop/current/*
