name: Automatic tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

# Cancel currently-running builds when pushing new commits to a PR.
# Prevent TICS qserver from running concurrently.
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Call spread and unit tests as reusable workflows. This is the most
  # dependable method by which to share the artifacts
  spread:
    uses: ./.github/workflows/spread.yaml
    secrets: inherit
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  code-coverage:
    needs: [spread, unit-tests]
    runs-on: [self-hosted, reactive, amd64, large-tiobe, noble]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage
        uses: actions/download-artifact@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install dependencies
        run: |
          . "$GITHUB_WORKSPACE/tests/lib/retry.sh"

          retry 5 go install github.com/axw/gocov/gocov@v1.1.0
          retry 5 go install github.com/AlekSi/gocov-xml@v1.1.0
          retry 5 go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Merge Coverage
        run: |
          COVERDIRS=$(find -mindepth 2 -type d -name cover | tr '\n' ',' | sed 's/.$//')
          mkdir .cover
          go tool covdata merge -i=$COVERDIRS -o .cover
          go tool covdata textfmt -i=$PWD/.cover -o coverage.out
          gocov convert coverage.out > coverage.json
          # coverage.xml must be in a .coverage folder.
          mkdir .coverage
          gocov-xml < coverage.json > .coverage/coverage.xml

      - name: Determine TICS mode
        id: tics-mode
        run: |
          if [[ "$GITHUB_EVENT_NAME" =~ ^(push|schedule)$ ]]; then
            mode=qserver
          else
            mode=client
          fi
          printf 'mode=%s\n' "$mode" >>"$GITHUB_OUTPUT"

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v3
        with:
          mode: ${{ steps.tics-mode.outputs.mode }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: workshop
          installTics: true
