name: Automatic tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

# Cancel currently-running builds when pushing new commits to a PR or branch
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Call spread and unit tests as reusable workflows. This is the most
  # dependable method by which to share the artifacts
  spread:
    uses: ./.github/workflows/spread.yaml
    secrets: inherit
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  code-coverage:
    needs: [spread, unit-tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage
        uses: actions/download-artifact@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.1.0

      - name: Merge Coverage
        run: |
          COVERDIRS=$(find -mindepth 2 -type d -name cover | tr '\n' ',' | sed 's/.$//')
          mkdir .cover
          go tool covdata merge -i=$COVERDIRS -o .cover
          go tool covdata textfmt -i=$PWD/.cover -o coverage.out
          gocov convert coverage.out > coverage.json
          # coverage.xml must be in a .coverage folder.
          mkdir .coverage
          gocov-xml < coverage.json > .coverage/coverage.xml

      # Qualification run, compares changes to a baseline
      - name: TICS GitHub Action
        if: false && github.ref != 'refs/heads/main'
        uses: tiobe/tics-github-action@v3
        with:
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: workshop
          installTics: true

      # Baseline (reference) run
      - name: TICS GitHub Action (Reference Run)
        if: false && github.ref == 'refs/heads/main'
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: workshop
          installTics: true
