name: Run doc coverage

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f docs/coverage_requirements.txt ]; then
            pip install -r docs/coverage_requirements.txt
          fi

      - name: Run coverage
        run: python coverage.py
        working-directory: docs

      - name: Check for changes, commit, and create PR if any
        run: |
          if git diff --exit-code; then
            echo "No changes detected, skipping commit and PR creation."
          else
            pr_branch="docs/coverage-$(date +'%Y%m%d%H%M%S')"
            git checkout -b $pr_branch
            
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            
            git add .
            git commit -m "Doc: Update doc coverage map"
            git push --set-upstream origin $pr_branch

            gh pr create --title "Doc: Update doc coverage map" --body "This PR updates the documentation coverage map." --base main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
