name: Check for fixup and squash commits

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          filter: 'tree:0'
          persist-credentials: true

      - name: Check history
        run: |
          if [ "$GITHUB_EVENT_NAME" != 'pull_request' ]; then
            printf '::error::This workflow only supports pull request events.\n'
            exit 1
          fi

          git fetch --filter=tree:0 --no-recurse-submodules origin "+${GITHUB_BASE_REF}:${GITHUB_BASE_REF}"

          log() {
            git log --pretty='format:%s (%h)' "${GITHUB_BASE_REF}..HEAD"
          }
          filter() {
            grep -E '^(fixup|squash)!' || [ $? -eq 1 ]
          }

          log | filter >log
          fixups=$(wc -l <log)

          if [ "$fixups" -ne 0 ]; then
            printf '::error::Found %d fixup! or squash! commit(s).\n' "$fixups"
            printf 'Found %d fixup! or squash! commit(s):\n```\n' "$fixups" >>"${GITHUB_STEP_SUMMARY}"
            tee -a "${GITHUB_STEP_SUMMARY}" <log >&2
            printf '```\n' >>"${GITHUB_STEP_SUMMARY}"
            exit 1
          fi
        shell: bash
