name: Lint
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/checkout@v6
        with:
          repository: canonical/snapd-testing-tools
          path: snapd-testing-tools	      
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        id: lint
        with:
          version: v2.10
          skip-cache: true

      - name: golangci-incremental
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          args: --config=.golangci.incremental.yaml
          only-new-issues: true
          skip-cache: true

      - name: shellcheck
        run: |
          git ls-files | file --mime-type -Nnf- | grep shellscript | cut -f1 -d: | xargs shellcheck --check-sourced --external-sources
          snapd-testing-tools/utils/spread-shellcheck tests/integration

      - name: Print error message
        if: always() && steps.lint.outcome == 'failure'
        run: |
          echo '
          Linting failed. On your local machine, please run
              golangci-lint run --fix
          and check in the changes.'
          exit 1
