name: LXD Candidate Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-deps:
    uses: ./.github/workflows/build-deps.yaml
    secrets: inherit
  snap-tests:
    needs: [build-deps]
    strategy:
      fail-fast: false
      matrix:
        suite: [main/, integration/]
    runs-on: [self-hosted, linux, jammy, x64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 6/candidate
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout Workshop
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false
      - name: Download Workshop Snap
        uses: actions/download-artifact@master
        with:
          name: snap_workshop
          path: ${{ github.workspace }}/tests/
      - name: Download Sdkcraft Snap
        uses: actions/download-artifact@master
        with:
          name: snap_sdkcraft
          path: ${{ github.workspace }}/tests/
      - name: Download spread binary
        uses: actions/download-artifact@master
        with:
          name: spread_binary
          path: /usr/local/bin
      - name: Install spread
        run: sudo chmod +x /usr/local/bin/spread
      - name: Set LXD storage size
        run: |
          lxc storage set default volume.size=32GB
      - name: Run spread
        run: |
          mkdir ${{ github.workspace }}.cover
          spread -artifacts=${{ github.workspace }}.cover tests/${{matrix.suite}}
