name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.11"
    - name: Create venv
      working-directory: "docs"
      run: make install
    - name: Lint markdown
      working-directory: "docs"
      run: make lint-md
