name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "3.11"
    - name: Create venv
      working-directory: "docs"
      run: make install
    - name: Lint markdown
      working-directory: "docs"
      run: make lint-md
