name: Vulnerability scanning

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run Github Trivy FS Action
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: .github/trivy.yaml
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          # TODO: Remove the whole "env" section when the issue below is resolved.
          # Known issue: aquasecurity/trivy-action#389.
          # Workaround: https://github.com/orgs/community/discussions/139074#discussioncomment-10808081.
