name: Release snap
on: [workflow_dispatch]

jobs:
  build:
    runs-on: [self-hosted, Linux, noble, X64, large]
    steps:
      - uses: actions/checkout@v4

      - uses: canonical/action-build@v1
        id: snapcraft

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.snapcraft.outputs.snap }}
