name: Spread
on: [workflow_dispatch, workflow_call]

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workshop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Sdkcraft
        uses: actions/checkout@v4
        with:
          repository: canonical/sdkcraft
          show-progress: true
          token: ${{ secrets.GH_SDKCRAFT }}
          path: sdkcraft
          fetch-depth: 0
      - name: Build Workshop
        uses: canonical/action-build@v1
        id: snapcraft
      - name: Upload Workshop
        uses: actions/upload-artifact@master
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - name: Build Sdkcraft
        uses: canonical/action-build@v1
        id: snapcraft_sdkcraft
        with:
          path: sdkcraft
      - name: Upload Sdkcraft
        uses: actions/upload-artifact@master
        with:
          name: snap_sdkcraft
          path: ${{ steps.snapcraft_sdkcraft.outputs.snap }}
  snap-tests:
    needs: build-snap
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-64]
        suite: [main, documentation, integration]
    runs-on: [self-hosted, linux, jammy, x64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 6/stable
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Pre-download LXD images
        run: |
          image_dir="$HOME/images"
          mkdir -p "$image_dir"

          for version in 22.04 24.04; do
            if [ ! -f "$image_dir/ubuntu-$version.tar.gz" ]; then
              lxc image copy "ubuntu:$version/amd64" local: --alias "$version/amd64"
              lxc image export "$version/amd64" "$image_dir/ubuntu-$version.tar.gz"
            fi
          done

          lxc project switch default
          lxc profile device add default mnt-image disk source=$image_dir path=/mnt
      - name: Checkout Workshop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - uses: actions/download-artifact@master
        with:
          name: snap
          path: ${{ github.workspace }}/tests/
      - uses: actions/download-artifact@master
        with:
          name: snap_sdkcraft
          path: ${{ github.workspace }}/tests/
      - name: Install spread
        run: |
          # go install is not supported for forks...
          git clone https://github.com/dmitry-lyfar/spread
          pushd spread
          go install ./...
          popd
      - name: Run spread
        run: |
          mkdir ${{ github.workspace }}.cover
          spread -artifacts=${{ github.workspace }}.cover tests/${{matrix.suite}}/
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-${{matrix.suite}}
          path: ${{ github.workspace }}.cover/lxd:ubuntu-24.04:tests/
          if-no-files-found: ignore
