name: Workshop end-to-end tests
on:
  workflow_call:
    secrets:
      GH_SDKCRAFT:
        required: true
      STORE_CREDENTIALS:
        required: true
      SDKCRAFT_STORE_CREDENTIALS:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deps:
    uses: ./.github/workflows/build-deps.yaml
    secrets:
      GH_SDKCRAFT: ${{ secrets.GH_SDKCRAFT }}
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS }}
  snap-tests:
    needs: [build-deps]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-64]
        suite:
          [
            main/,
            docs-how-to/,
            docs-tutorial/part-1,
            docs-tutorial/part-2,
            docs-tutorial/part-3,
            docs-tutorial/part-4,
            integration/,
          ]
    runs-on: [self-hosted, linux, jammy, x64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee # v1
        with:
          channel: 6/stable
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout Workshop
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26"
          cache: false
      - name: Download Workshop Snap
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: snap_workshop
          path: ${{ github.workspace }}/tests/
      - name: Download Sdkcraft Snap
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: snap_sdkcraft
          path: ${{ github.workspace }}/tests/
      - name: Download spread binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: spread_binary
          path: /usr/local/bin
      - name: Install spread
        run: sudo chmod +x /usr/local/bin/spread
      - name: Set LXD storage size
        run: |
          lxc storage set default volume.size=32GB
      - name: Run spread
        run: |
          mkdir ${{ github.workspace }}.cover
          spread -artifacts=${{ github.workspace }}.cover tests/${{matrix.suite}}
        env:
          TEST_SDK_BRANCH: ${{ needs.build-deps.outputs.test_sdk_branch }}
      - name: Trim trailing slash from matrix.suite
        id: sanitize
        env:
          SUITE_NAME: ${{ matrix.suite }}
        run: |
          echo "sanitized_name=${SUITE_NAME%/}" >> "$GITHUB_OUTPUT"
      - name: Upload Coverage
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: code-coverage-${{ steps.sanitize.outputs.sanitized_name }}
          path: ${{ github.workspace }}.cover/lxd:ubuntu-24.04:tests/
          if-no-files-found: ignore
  publish:
    needs: [build-deps, snap-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: snap_workshop
      - uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # v1.2.0
        if: github.event_name == 'push'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }} # zizmor: ignore[secrets-outside-env]
        with:
          snap: ${{ needs.build-deps.outputs.snap_workshop }}
          release: edge
