name: Workshop end-to-end tests
on: [workflow_dispatch, workflow_call]

jobs:
  build-deps:
    uses: ./.github/workflows/build-deps.yaml
    secrets: inherit
  snap-tests:
    needs: [build-deps]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-64]
        suite: [main/, docs-how-to/, docs-tutorial/part-1, docs-tutorial/part-2, docs-tutorial/part-3, docs-tutorial/part-4, integration/]
    runs-on: [self-hosted, linux, jammy, x64, xlarge]
    steps:
      - name: Install LXD
        uses: canonical/setup-lxd@v1
        with:
          channel: 6/stable
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout Workshop
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false
      - name: Download Workshop Snap
        uses: actions/download-artifact@master
        with:
          name: snap_workshop
          path: ${{ github.workspace }}/tests/
      - name: Download Sdkcraft Snap
        uses: actions/download-artifact@master
        with:
          name: snap_sdkcraft
          path: ${{ github.workspace }}/tests/
      - name: Download spread binary
        uses: actions/download-artifact@master
        with:
          name: spread_binary
          path: /usr/local/bin
      - name: Install spread
        run: sudo chmod +x /usr/local/bin/spread
      - name: Set LXD storage size
        run: |
          lxc storage set default volume.size=32GB
      - name: Run spread
        run: |
          mkdir ${{ github.workspace }}.cover
          spread -artifacts=${{ github.workspace }}.cover tests/${{matrix.suite}}
      - name: Trim trailing slash from matrix.suite
        id: sanitize
        env:
          SUITE_NAME: ${{ matrix.suite }}
        run: |
          echo "sanitized_name=${SUITE_NAME%/}" >> "$GITHUB_OUTPUT"
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-${{ steps.sanitize.outputs.sanitized_name }}
          path: ${{ github.workspace }}.cover/lxd:ubuntu-24.04:tests/
          if-no-files-found: ignore
  publish:
    needs: [build-deps, snap-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: snap_workshop
      - uses: canonical/action-publish@v1
        if: github.event_name == 'push'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
        with:
          snap: ${{ needs.build-deps.outputs.snap_workshop }}
          release: edge
