name: Check for staged SDKs

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check for staged SDKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check for staged SDKs
        run: |
          if [ -d tests/lib/staging ]; then
            printf '::error::Found staged SDKs, please move them to tests/lib/sdk before merging.\n'
            exit 1
          fi
