name: Unit Tests
on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: mkdir -p ${{ github.workspace }}.cover/unit/cover && go test -cover -coverpkg=./... ./... -args -test.gocoverdir=${{ github.workspace }}.cover/unit/cover

      - name: Upload Coverage
        id: upload-coverage
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: code-coverage-unit
          path: ${{ github.workspace }}.cover/
  race:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25"

      - name: Check for races
        run: go test -race ./...
